### ISSUE TITLE
way to confirm channel subscription

### ISSUE THREAD

**Issue by rickybrown** [nolancaster/angular2-actioncable#1]
looking to auto-send a message immediately after a successful subscription. also wondering if there are additional feature plans for this project

**Comment by nolancaster** [comment]
Looking at the actioncable code, there might be a way to add this. I'm thinking you might be safe to assume the subscription is created as soon as the `.channel()` method is finished, though.

One thing I'm definitely looking at adding is the ability to monitor the status of a connection. I have a scenario now where I need to see if I've been disconnected and then attempt to reconnect with a fresh authentication token.

**Comment by rickybrown** [comment]
i have that exact same scenario now, needing to know connection status. will try to come up with something

**Comment by nolancaster** [comment]
@rickybrown If you still need this feature, I just published version 1.2.0 that adds a Channel.connected() method that will notify you off a successful subscription.
